# #####################################################################
config:
# Concat
  concat:
    ACTIVE_CONCAT: TRUE
    babelconcat: app
    namejs: plugins
    namecss: plugins
    namejs_core: core
    namecss_core: core
    js_core:
      # - "bower_components/Modernizr/modernizr.custom.js"
      - "bower_components/jquery/dist/jquery.js"
      # - "bower_components/lodash/dist/lodash.min.js"
      - "bower_components/tether/dist/js/tether.js"
      - "bower_components/bootstrap/popper.js"
      - "bower_components/bootstrap/dist/js/bootstrap.js"
      - "bower_components/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.js"
      - "bower_components/moment/min/moment.min.js"
      - "bower_components/scrollup/dist/jquery.scrollUp.js"
    css_core:
      - "bower_components/animate.css/animate.css"
      # - "bower_components/bootstrap/dist/css/bootstrap.css"
      - "bower_components/bootstrap-datepicker-master/dist/css/bootstrap-datepicker.css"
      - "bower_components/font-awesome/css/font-awesome.css"
      - "bower_components/hover/css/hover.css"
    js:
      - "bower_components/wow/dist/wow.js"
      - "bower_components/slick-carousel/slick/slick.js"
      - "bower_components/ScrollToFixed/jquery-scrolltofixed.js"
      - "bower_components/responsive-tabs/js/jquery.responsiveTabs.js"
      - "bower_components/jquery.tickerNews-master/jquery.tickerNews.js"
      - "bower_components/jquery-bar-rating/dist/jquery.barrating.min.js"
      - "bower_components/offline/offline.min.js"
      # - "bower_components/owl.carousel/dist/owl.carousel.min.js"
      # - "bower_components/k-gmaps/dist/js/kmaps.js"
      # - "bower_components/bootstrap-validator/dist/validator.min.js"
      # - "bower_components/bootstrap-offcanvas/dist/js/bootstrap.offcanvas.js"
      # - "bower_components/select2/dist/js/select2.full.min.js"
      # - "bower_components/jquery-lazy/jquery.lazy.min.js"
      # - "bower_components/lightgallery/dist/js/lightgallery.min.js"
    css:
      - "bower_components/linearicons/icon-font.min.css"
      - "bower_components/slick-carousel/slick/slick.css"
      - "bower_components/slick-carousel/click/slick-theme.css"
      - "bower_components/k-flex/dist/css/k-flex.css"
      - "bower_components/responsive-tabs/css/responsive-tabs.css"
      - "bower_components/jquery-bar-rating/dist/themes/fontawesome-stars.css"
      # - "bower_components/offline/themes/offline-theme-default.css"
      # - "bower_components/offline/themes/offline-language-english.css"
      # - "bower_components/owl.carousel/dist/assets/owl.carousel.min.css"
      # - "bower_components/owl.carousel/dist/assets/owl.theme.default.css"
      # - "bower_components/bootstrap-offcanvas/dist/css/bootstrap.offcanvas.css"
      # - "bower_components/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css"
      # - "bower_components/select2/dist/css/select2.min.css"
      # - "bower_components/lightgallery/dist/css/lightgallery.min.css"
# SEO
  SEO:
    AppName: "Home"
    mobile_color: "#fff"
    cfg_name: "DEMO SITE"
    cfg_url: "demo-site.com"
    analytics: 'UA-XXXXXXXXXXX-1'
    seo_lang: 'en'
    seo_geo: 'EN' # Check at http://en.mygeoposition.com/
    seo_geo_latitude: '36.204824'
    seo_geo_longitude: '138.252924'
    app_facebook_ID: '100000511421818'
    cfg_description: "I’ve been designing profesionally since 2003. I founded GC Com in 2008."
    cfg_keywords: "Bao Nguyen, Bảo Nguyên, Brands Designer, Web Developer, Apps Developer, Photograper, Front-End Developer"
    cfg_author: "Bao Nguyen"
    cfg_sitenameurl: "baonguyenyam"
    app_facebook_adminsID: 'XXXXXXX,XXXXXXX'
    app_appleID: 'XXX-XXX-XXX-XXXX'
    cfg_sitenameurlgoogle: "XXXXXXXXXXXXXX"
    verf_google: "VhfbPndGW-UftEvWql2Nwt7F1F5KBgd3lMcGgjn4Ovc"
    verf_bing: "F7679394C660249FBA58732D6100A65A"
    verf_yandex: "bc82adfacdd74cbf"
# #####################################################################
# Base config
  url: "./"
  baseUrl: "./"
  source: "src"
  views: "src/views"
  dest: "html"
  tmp: "tmp"
  docs: "docs"
  test: "test"
  favicon: "resources/favicon.png"
  favicondist: "/favicon/"
  resources: "resources"
  config: "config"
  fonts: "fonts"
  data: "data"
  dataJS: "scripts"
  blank: "_blank"
  images: "images"
# Layout
  layouts:
    assets: "partials"
    root: "templates"
    jade: "templates"
    nunjucks: "templates/nunjucks"
# Scripts
  scripts:
    assets: "js"
    root: "scripts"
    typescript: "scripts/typescript"
    javascript: "scripts"
    coffee: "scripts/coffee"
# Styles
  styles:
    assets: "css"
    root: "styles"
    css: "styles/css"
    less: "styles/less"
    sass: "styles"
    stylus: "styles/stylus"
# CleanUp
  cleanup: "{favicon.json,rev-manifest.json}"
# Ignore
  ignore:
    copy: "{**/*.jade,**/*.nunjucks,**/*.js,**/*.ts,**/*.coffee}"
    scripts: "{**/*.ts,**/*.coffee}"
    jade: "{include,include/**}"
    nunjucks: "{include,include/**}"
    concat: "{config.js,core,core/**/*.js}"
    concatactiveconcat: "{config.js,core,core/**/*.js,pages,pages/**/*.js}"
    sass: "{includes,includes/**,common,common/**,mixins,mixins/**}"
    sassactiveconcat: "{includes,includes/**,common,common/**,mixins,mixins/**,pages,pages/**}"
    inject: "{pages,pages/**}"
    stylus: "{include,include/**}"
    css: "{include,include/**}"
    less: "{include,include/**}"
    test: "{vendor,vendor/**}"
# Config Host
  host: "127.0.0.1"
  port: "8084"
  sameport: "6084"
  proxy: "9018"
  website: "baonguyenyam.github.io"
# Packer
  packer: main.js
  packerdist: app.js #to app.min.js
# License
  title: "Gulp App"
  author:
    email: "baonguyenyam@gmail.com"
    name: "BaoNguyen"
    phone: "0969689893 - 0933112900"
    link: "https://baonguyenyam.github.io"
    coding: "Coding by Bao Nguyen"
  license: "MIT"
  name: "Bao Nguyen Apps"
  version: "1.0"
